spring:
  application:
    name: desafio-processo-seletivo-seplag-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: ${POSTGRES_URL}/desafio-processo-seletivo-seplag-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB


springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    filter: true
    path: /swagger-ui.html


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /monitoramento

s3:
  endpoint: ${STORAGE_ENDPOINT}
  bucket-name: ${STORAGE_BUCKET_NAME}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}

server:
  port: 26000