version: "3.8"

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db
      - minio
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_BUCKET_NAME: desafio-processo-seletivo-seplag-bucket
      STORAGE_ACCESS_KEY: user
      STORAGE_SECRET_KEY: 12345678

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=desafio-processo-seletivo-seplag-db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_db:/volumes/data/postgres
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app_network
    volumes:
      - minio_db:/volumes/data/minio
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=desafio-processo-seletivo-seplag-bucket

networks:
  app_network:
    driver: bridge

volumes:
  minio_db:
    driver: local
  postgres_db:
    driver: local
