version: "3.8"

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      STORAGE_ENDPOINT: http://localhost:9000
      STORAGE_BUCKET_NAME: desafio-processo-seletivo-seplag-bucket
      STORAGE_ACCESS_KEY: user
      STORAGE_SECRET_KEY: 12345678

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      -  postgres_network
    volumes:
      - db:/volumes/data/postgres

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      -  '9000:9000'
      -  '9001:9001'
    networks:
      -  minio_network
    volumes:
      - minio_db:/volumes/data/minio
    environment:
      -  MINIO_ROOT_USER=user
      -  MINIO_ROOT_PASSWORD=12345678
      -  MINIO_DEFAULT_BUCKETS=desafio-processo-seletivo-seplag-bucket

networks:
  minio_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  minio_db:
    driver: local
  postgres:
    driver: local